import torch
from transformers import AutoTokenizer, pipeline, RobertaForSequenceClassification

climatebert_tokenizer = AutoTokenizer.from_pretrained("climatebert/distilroberta-base-climate-f")
climate_attention_model = RobertaForSequenceClassification.from_pretrained('kruthof/climateattention-ctw',
                                                                           num_labels=2)


def is_about_climate(texts):
    device = 0 if torch.cuda.is_available() else -1
    pipe = pipeline("text-classification", model=climate_attention_model,
                    tokenizer=climatebert_tokenizer, device=device)
    labels = []
    probs = []
    for out in pipe(texts, batch_size=64):
        labels.append(out['label'])
        probs.append(out['score'])
    return labels, probs


if __name__ == '__main__':
    print(is_about_climate(['Global warming first became evident beyond the bounds of natural variability in 1970s, but increases global mean surface temperatures have stalled 2000s. Increases atmospheric greenhouse gases, notably carbon dioxide, create an energy imbalance at top-of-atmosphere (TOA) even as planet warms to adjust this imbalance, which is estimated be 0.5–1 W m−2 over Annual fluctuations TOA up 0.2 W m−2 occur from variations clouds, aerosols, and changes Sun. At times major volcanic eruptions effects can much larger. Yet fluctuate more than these account for. An manifested not just or ground also melting sea land ice, heating oceans. More 90% heat goes into oceans and, with causes level rise. For past decade, 30% has apparently penetrated below 700 m depth that traceable winds mainly Pacific association a switch negative phase Decadal Oscillation (PDO) 1999. Surface was evidence during 1976–1998 positive PDO, suggesting decadal modulates rate change while sea-level rise relentless. stopped; it merely different ways.',
                            'Dioecious plant species represent an important component of terrestrial ecosystems. Yet, little is known about sex-specific responses to drought and elevated temperatures. Populus cathayana Rehd, which a dioecious, deciduous tree species, widely distributed in the northern, central southwestern regions China, was employed as model our study. In closed-top chamber experiments, morphological, physiological biochemical P. different temperatures were investigated. Compared with controls, significantly decreased growth net photosynthesis rate (A), increased intrinsic water use efficiency (WUE(i)), carbon isotope composition (delta13C), malondialdehyde (MDA) abscisic acid (ABA) contents droughted plants. contrast, promoted A, but WUE(i), delta13C, MDA ABA well-watered individuals. When compared males, induced females express greater increase height (HG), basal diameter (BD), leaf area (LA), total number leaves (TNL), dry matter accumulation (DMA) specific (SLA), lower decrease A value, transpiration (E), stomatal conductance (g(s)), contents, while drought-stressed exhibit values HG, BD, LA, TNL, DMA, E, g(s) intercellular CO2 concentration (C(i)), higher levels SLA, contents. Our results indicated that female individuals are more responsive suffer from negative effects than do males when grown under environments stress temperature.',
                            'Papilio canadensis encounters shorter, cooler summers in interior Alaska than northern Michigan: average thermal sums are 583 vs. 985 Celsius degree—days (10°C base); mean daily temperature is 14.4 18.8°. The physiology of P. could be evolutionarily conserved, or the species may a composite regionally adapted populations. We evaluated these hypotheses by comparing developmental from and Michigan across range temperatures laboratory field. Higher generally resulted more rapid larval development, but effects varied with insect population host. At low (12°), Alaskan larvae grew faster (fifth instars doubled their fresh mass 5.8 9.1 d), primarily due to 40% higher consumption rates. high (30°), slower, faster, same as larvae, depending upon Effects host quality were greatest at temperatures. Elevated respiratory expenses (35% larvae) made them especially sensitive Dry matter digestibility nitrogen use efficiency differed hosts, not between populations Molting accounted for 35—51% development time. completed fifth molt 12° (11.8 17.8 30° (3.1 2.9 d). In both populations, was growth (Q10 5.65 3.04 12 18°), less 1.60 2.06 18 30°). Survival temperatures, Under ideal basking conditions, field able elevate body °10° above ambient, such conditions rare usually near ambient temperature. no better selecting radiation microsites converting solar into heat. Growth rates when fed foliage exposed air incorporated responses life history model, then used 48—yr climatic record evaluate fitness contributions apparent adaptations summers. On good host, had an estimated 3.0 times greater canadensis. Furthermore, predicted go extinct 31 48 yr Changes contribution enhanced Alaska, followed increased neonates, molting abilities reduced size threshold pupation. Analysis trade—offs suggested that extreme have been important shaping adaptive responses. Regional adaptation climate allows maintain broader geographic distribution would otherwise possible, limits probably still constrained summer']))
